# Generated by Django 6.0.4 on 2026-04-15 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
        ('securities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('value', models.DecimalField(decimal_places=6, max_digits=16, null=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='securities.security')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['security', 'name', 'date'], name='prices_indi_securit_67fdbc_idx')],
                'unique_together': {('security', 'date', 'name')},
            },
        ),
    ]
