# Generated by Django 6.0.4 on 2026-04-15 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_indicator'),
        ('securities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntradayBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('open', models.DecimalField(decimal_places=4, max_digits=12)),
                ('high', models.DecimalField(decimal_places=4, max_digits=12)),
                ('low', models.DecimalField(decimal_places=4, max_digits=12)),
                ('close', models.DecimalField(decimal_places=4, max_digits=12)),
                ('volume', models.BigIntegerField()),
                ('vwap', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('trade_count', models.IntegerField(blank=True, null=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intraday_bars', to='securities.security')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['security', 'timestamp'], name='prices_intr_securit_b3a247_idx')],
                'unique_together': {('security', 'timestamp')},
            },
        ),
    ]
