# Generated by Django 6.0.4 on 2026-04-15 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(max_length=100)),
                ('symbols', models.JSONField()),
                ('parameters', models.JSONField()),
                ('capital', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('stopped', 'Stopped'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('symbol_states', models.JSONField(blank=True, default=dict)),
                ('total_pnl', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('direction', models.CharField(max_length=10)),
                ('entry_price', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('exit_price', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('shares', models.DecimalField(decimal_places=6, max_digits=14, null=True)),
                ('pnl', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('exit_reason', models.CharField(blank=True, max_length=50)),
                ('alpaca_order_id', models.CharField(blank=True, max_length=100)),
                ('entry_time', models.DateTimeField(null=True)),
                ('exit_time', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trading.livesession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
