# Generated by Django 6.0.4 on 2026-04-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='margin_multiplier',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='livesession',
            name='mode',
            field=models.CharField(choices=[('stock', 'Stock Only'), ('hybrid', 'Hybrid (Stock + Options)')], default='stock', max_length=20),
        ),
        migrations.AddField(
            model_name='livesession',
            name='options_trades_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='livesession',
            name='trades_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='livesession',
            name='use_margin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livetrade',
            name='contracts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livetrade',
            name='instrument_type',
            field=models.CharField(choices=[('stock', 'Stock'), ('option', 'Option')], default='stock', max_length=10),
        ),
        migrations.AddField(
            model_name='livetrade',
            name='option_symbol',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
