# Generated by Django 6.0.4 on 2026-04-15 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('securities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backtest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(max_length=100)),
                ('parameters', models.JSONField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('initial_capital', models.DecimalField(decimal_places=2, default=10000, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('total_return_pct', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('sharpe_ratio', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('max_drawdown_pct', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('win_rate_pct', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('profit_factor', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('total_trades', models.IntegerField(null=True)),
                ('avg_trade_duration_minutes', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('equity_curve', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtests', to='securities.security')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OptimizationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('n_trials', models.IntegerField(default=100)),
                ('objective_metric', models.CharField(default='sharpe_ratio', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('study_name', models.CharField(max_length=200, unique=True)),
                ('best_params', models.JSONField(blank=True, null=True)),
                ('best_value', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('trials_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('best_backtest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optimization_source', to='backtests.backtest')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimization_runs', to='securities.security')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=10)),
                ('entry_timestamp', models.DateTimeField()),
                ('exit_timestamp', models.DateTimeField(blank=True, null=True)),
                ('entry_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('shares', models.DecimalField(decimal_places=6, max_digits=14)),
                ('pnl', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('pnl_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('commission', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('exit_reason', models.CharField(blank=True, choices=[('stop_loss', 'Stop Loss'), ('take_profit', 'Take Profit'), ('eod', 'End of Day'), ('signal', 'Signal')], max_length=20)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('backtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='backtests.backtest')),
            ],
            options={
                'ordering': ['entry_timestamp'],
            },
        ),
    ]
