# Generated by Django 6.0.4 on 2026-04-15 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='sortino_ratio',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
    ]
